<?php

/**
 * @file
 * Default template for HTML Mail
 *
 * HMTL Mail will first look in the directory of the current theme for a file
 * named "htmlmail.tpl.php". If found, it will be used to format emails.
 * Otherwise, this file will be used instead.
 *
 * DO NOT EDIT THIS FILE. Copy it to your theme directory, and edit the copy.
 *
 * The following variables are available in this template:
 *
 *  - $body      : message body
 *  - $key       : message id
 *  - $header    : template header
 *  - $footer    : template footer
 *  - $css       : template css
 *  - $directory : directory containing the theme template
 *  - $path      : absolute URL of the theme directory (for images, etc)
 *
 * For tips and resources on building HTML emails see:
 * http://www.campaignmonitor.com/css/
 * http://www.mailchimp.com/articles/email_marketing_guide/
 * http://css-tricks.com/using-css-in-html-emails-the-real-story/
 *
 */

?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<?php if ($css): ?>
<style type="text/css">
<?php print $css; ?>
</style>
<?php endif; ?>
</head>

<body class="htmlmail">
<table width="100%" border="0" cellspacing="0" cellpadding="5">
  <tr>
    <td valign="top" align="center">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
        <?php if ($header): ?>
        <tr>
          <td valign="top" class="htmlmail-header">
          <?php print $header; ?>
          </td>
        </tr>
        <?php endif; ?>
        <tr>
          <td valign="top" class="htmlmail-body">
          <?php print $body; ?>
          </td>
        </tr>
        <?php if ($footer): ?>
        <tr>
          <td valign="top" class="htmlmail-footer">
            <?php print $footer; ?>
          </td>
        </tr>
        <?php endif; ?>
     </table>
   </td>
 </tr>
</table>
</body>
</html>
